# Generated by Django 4.2.30 on 2026-09-25 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_duplicatecandidate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadgrid',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='边界有效开始（含，NULL=最早）'),
        ),
        migrations.AddField(
            model_name='roadgrid',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='边界有效结束（不含，NULL=最晚）'),
        ),
        migrations.AlterField(
            model_name='penaltyversion',
            name='kind',
            field=models.CharField(choices=[('initial', '初版立案'), ('escalation', '逾期升级'), ('correction', '人工更正'), ('attribution', '追溯归属更正')], max_length=16, verbose_name='版本类型'),
        ),
        migrations.CreateModel(
            name='RevisionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('proposal_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='提案编号')),
                ('status', models.CharField(choices=[('draft', '待确认'), ('published', '已发布'), ('withdrawn', '已撤回'), ('superseded', '已被替代'), ('rejected', '校验拒绝')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('target_type', models.CharField(choices=[('grid', '道路网格'), ('contract', '保洁合同')], max_length=16, verbose_name='修订对象类型')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='修订有效开始（含）')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='修订有效结束（不含）')),
                ('reason', models.CharField(max_length=512, verbose_name='修订原因')),
                ('actor', models.CharField(blank=True, default='', max_length=64, verbose_name='提案人')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='幂等键')),
                ('new_contractor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='修订后承包商')),
                ('new_valid_from', models.DateTimeField(blank=True, null=True, verbose_name='修订后责任开始（含）')),
                ('new_valid_to', models.DateTimeField(blank=True, null=True, verbose_name='修订后责任结束（不含）')),
                ('new_name', models.CharField(blank=True, default='', max_length=128, verbose_name='修订后网格名称')),
                ('new_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='修订后网格范围')),
                ('baseline_grid_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='基准网格范围')),
                ('baseline_grid_effective_from', models.DateTimeField(blank=True, null=True, verbose_name='基准网格有效开始')),
                ('baseline_grid_effective_to', models.DateTimeField(blank=True, null=True, verbose_name='基准网格有效结束')),
                ('baseline_contractor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='基准承包商')),
                ('baseline_valid_from', models.DateTimeField(blank=True, null=True, verbose_name='基准合同开始')),
                ('baseline_valid_to', models.DateTimeField(blank=True, null=True, verbose_name='基准合同结束')),
                ('baseline_grid_id', models.BigIntegerField(blank=True, null=True, verbose_name='基准合同所属网格ID')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('published_by', models.CharField(blank=True, default='', max_length=64, verbose_name='发布人')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=512, verbose_name='拒绝原因')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision_proposals', to='assessment.cleaningcontract', verbose_name='目标合同（合同修订）')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_proposals', to='assessment.roadgrid', verbose_name='目标/相关网格')),
                ('new_grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_contract_proposals', to='assessment.roadgrid', verbose_name='改挂网格（合同责任区迁移）')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='assessment.revisionproposal', verbose_name='替代本提案的新提案')),
            ],
            options={
                'verbose_name': '修订提案',
                'verbose_name_plural': '修订提案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionImpactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(choices=[('unlocked_attribution', '未锁定：确认后改挂归属'), ('locked_correction', '已锁定：追加更正/复核'), ('unresolved', '无法解析（断档/重叠）'), ('future', '未来事件，本次不调整'), ('photo_only', '仅关联照片（信息项）')], max_length=24, verbose_name='处置类型')),
                ('state', models.CharField(choices=[('pending', '待确认'), ('applied', '已应用'), ('skipped', '已跳过')], default='pending', max_length=16, verbose_name='处理状态')),
                ('from_contractor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='修订前承包商')),
                ('to_contractor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='修订后承包商')),
                ('note', models.CharField(blank=True, default='', max_length=512, verbose_name='说明')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision_impacts', to='assessment.problemevent', verbose_name='受影响事件')),
                ('from_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_items_from', to='assessment.cleaningcontract', verbose_name='修订前归属合同')),
                ('from_grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_items_from_grid', to='assessment.roadgrid', verbose_name='修订前网格')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision_impacts', to='assessment.penaltyunit', verbose_name='受影响处罚')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision_impacts', to='assessment.evidencephoto', verbose_name='受影响照片')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_items', to='assessment.revisionproposal', verbose_name='修订提案')),
                ('to_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_items_to', to='assessment.cleaningcontract', verbose_name='修订后归属合同')),
                ('to_grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impact_items_to_grid', to='assessment.roadgrid', verbose_name='修订后网格')),
            ],
            options={
                'verbose_name': '修订影响项',
                'verbose_name_plural': '修订影响项',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GridHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='网格编号快照')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='网格名称快照')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='网格范围快照')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='边界有效开始（含，NULL=最早）')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='边界有效结束（不含，NULL=最晚）')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='assessment.roadgrid', verbose_name='道路网格')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grid_history_rows', to='assessment.revisionproposal', verbose_name='发布该快照的修订（NULL=迁移基线）')),
            ],
            options={
                'verbose_name': '网格历史快照',
                'verbose_name_plural': '网格历史快照',
                'ordering': ['grid_id', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='合同编号快照')),
                ('contractor_name', models.CharField(max_length=128, verbose_name='承包商名称快照')),
                ('valid_from', models.DateTimeField(verbose_name='责任开始时间快照（含）')),
                ('valid_to', models.DateTimeField(verbose_name='责任结束时间快照（不含）')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='assessment.cleaningcontract', verbose_name='保洁合同')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_history_rows', to='assessment.roadgrid', verbose_name='网格快照')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_history_rows', to='assessment.revisionproposal', verbose_name='发布该快照的修订（NULL=迁移基线）')),
            ],
            options={
                'verbose_name': '合同历史快照',
                'verbose_name_plural': '合同历史快照',
                'ordering': ['contract_id', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttributionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_contractor_name', models.CharField(max_length=128, verbose_name='更正前承包商（保留快照）')),
                ('to_contractor_name', models.CharField(max_length=128, verbose_name='应归承包商')),
                ('actor', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('from_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribution_corrections_from', to='assessment.cleaningcontract', verbose_name='更正前合同（保留）')),
                ('impact_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_corrections', to='assessment.revisionimpactitem', verbose_name='影响项')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_corrections', to='assessment.penaltyunit', verbose_name='处罚单元')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_corrections', to='assessment.revisionproposal', verbose_name='修订提案')),
                ('to_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribution_corrections_to', to='assessment.cleaningcontract', verbose_name='应归合同')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_corrections', to='assessment.penaltyversion', verbose_name='追加的归属版本')),
            ],
            options={
                'verbose_name': '归属更正审计',
                'verbose_name_plural': '归属更正审计',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='revisionproposal',
            index=models.Index(fields=['target_type', 'status'], name='assessment__target__0a6cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionproposal',
            index=models.Index(fields=['grid', 'status'], name='assessment__grid_id_95d764_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisionproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uniq_revision_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='revisionproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft'), ('target_type', 'contract')), fields=('contract',), name='uniq_draft_contract_revision'),
        ),
        migrations.AddConstraint(
            model_name='revisionproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft'), ('target_type', 'grid')), fields=('grid',), name='uniq_draft_grid_revision'),
        ),
        migrations.AddIndex(
            model_name='revisionimpactitem',
            index=models.Index(fields=['proposal', 'disposition'], name='assessment__proposa_056537_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionimpactitem',
            index=models.Index(fields=['state'], name='assessment__state_475936_idx'),
        ),
        migrations.AddIndex(
            model_name='gridhistory',
            index=models.Index(fields=['grid', 'effective_from', 'effective_to'], name='assessment__grid_id_7a7205_idx'),
        ),
        migrations.AddIndex(
            model_name='contracthistory',
            index=models.Index(fields=['grid', 'valid_from', 'valid_to'], name='assessment__grid_id_831b11_idx'),
        ),
    ]
