# Generated by Django 4.2.30 on 2026-09-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_duplicatecandidate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('revision_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='修订编号')),
                ('target_kind', models.CharField(choices=[('grid_boundary', '责任区边界修订'), ('contract_interval', '合同责任区间修订')], max_length=20, verbose_name='修订对象类型')),
                ('baseline_snapshot', models.JSONField(default=dict, verbose_name='基准快照（修订前登记状态）')),
                ('proposed_payload', models.JSONField(default=dict, verbose_name='修订内容（新边界/新合同责任）')),
                ('effective_from', models.DateTimeField(verbose_name='生效时间（含）')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='生效结束时间（不含）')),
                ('reason', models.CharField(blank=True, max_length=512, verbose_name='修订原因')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('published', '已发布'), ('withdrawn', '已撤回'), ('superseded', '已被替代')], default='pending', max_length=16, verbose_name='状态')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='幂等键')),
                ('impact_summary', models.JSONField(default=dict, verbose_name='影响汇总')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='提案人')),
                ('previewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近预览时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('published_by', models.CharField(blank=True, default='', max_length=64, verbose_name='发布人')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('withdrawn_by', models.CharField(blank=True, default='', max_length=64, verbose_name='撤回人')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessment.roadgrid', verbose_name='目标网格')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_revisions', to='assessment.responsibilityrevision', verbose_name='本修订替代的旧修订')),
                ('target_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessment.cleaningcontract', verbose_name='被修订合同（为空表示新增合同）')),
            ],
            options={
                'verbose_name': '责任区/合同修订',
                'verbose_name_plural': '责任区/合同修订',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='penaltyversion',
            name='kind',
            field=models.CharField(choices=[('initial', '初版立案'), ('escalation', '逾期升级'), ('correction', '人工更正'), ('revision', '归属修订')], max_length=16, verbose_name='版本类型'),
        ),
        migrations.CreateModel(
            name='RevisionImpactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_kind', models.CharField(choices=[('event', '问题事件'), ('penalty', '处罚单元'), ('photo', '证据照片')], max_length=16, verbose_name='对象类型')),
                ('disposition', models.CharField(choices=[('reassign_pending', '待确认调整（确认后改归属）'), ('locked_audit', '已锁定保留快照（追加审计链）'), ('photo_context', '证据照片归属上下文变化'), ('unresolved', '修订后无法归属（阻断确认）')], max_length=20, verbose_name='处置方式')),
                ('old_contract_code', models.CharField(blank=True, default='', max_length=32, verbose_name='原合同编号快照')),
                ('new_contract_code', models.CharField(blank=True, default='', max_length=32, verbose_name='新合同编号快照')),
                ('old_contractor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='原承包商快照')),
                ('new_contractor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='新承包商快照')),
                ('applied', models.BooleanField(default=False, verbose_name='是否已随发布生效')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_impacts', to='assessment.problemevent', verbose_name='受影响事件')),
                ('new_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessment.cleaningcontract', verbose_name='新合同')),
                ('new_grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessment.roadgrid', verbose_name='新网格')),
                ('old_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessment.cleaningcontract', verbose_name='原合同')),
                ('old_grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessment.roadgrid', verbose_name='原网格')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_impacts', to='assessment.penaltyunit', verbose_name='受影响处罚单元')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_impacts', to='assessment.evidencephoto', verbose_name='受影响照片')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_items', to='assessment.responsibilityrevision', verbose_name='修订')),
            ],
            options={
                'verbose_name': '修订影响明细',
                'verbose_name_plural': '修订影响明细',
                'ordering': ['revision_id', 'id'],
                'indexes': [models.Index(fields=['revision', 'item_kind'], name='assessment__revisio_8f3a57_idx'), models.Index(fields=['penalty'], name='assessment__penalty_326f57_idx'), models.Index(fields=['event'], name='assessment__event_i_588030_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='responsibilityrevision',
            index=models.Index(fields=['status', 'target_kind'], name='assessment__status_6c1800_idx'),
        ),
        migrations.AddIndex(
            model_name='responsibilityrevision',
            index=models.Index(fields=['grid', 'effective_from', 'effective_to'], name='assessment__grid_id_3b1067_idx'),
        ),
    ]
